development:
  adapter: postgresql
  host: 127.0.0.1
  database: <%=ENV['ENV_DB_NAME'] %>
  username: <%= ENV['ENV_DB_USERNAME'] %>
  password: <%= ENV['ENV_DB_PASSWORD'] %>
  encoding: unicode
  pool: 50
test:
  adapter: postgresql
  host: 127.0.0.1
  database: <%= ENV['TEST_DB_NAME'] %>
  username: <%= ENV['DB_USER_NAME'] %>
  password: <%= ENV['DB_PASSWORD'] %>
  encoding: unicode
  pool: 50
production:
  adapter: postgresql
  host: <%= ENV['ENV_DB_HOST'] %>
  database: <%=ENV['ENV_DB_NAME'] %>
  username: <%= ENV['ENV_DB_USERNAME'] %>
  password: <%= ENV['ENV_DB_PASSWORD'] %>
  port: <%= ENV['ENV_DB_PORT'] %>
  encoding: unicode
  pool: 50
staging:
  adapter: postgresql
  host: <%= ENV['ENV_DB_HOST'] %>
  database: <%=ENV['ENV_DB_NAME'] %>
  username: <%= ENV['ENV_DB_USERNAME'] %>
  password: <%= ENV['ENV_DB_PASSWORD'] %>
  port: <%= ENV['ENV_DB_PORT'] %>
  encoding: unicode
  pool: 50
qa:
  adapter: postgresql
  host: <%= ENV['ENV_DB_HOST'] %>
  database: <%= ENV['ENV_DB_NAME'] %>
  username: <%= ENV['ENV_DB_USERNAME'] %>
  password: <%= ENV['ENV_DB_PASSWORD'] %>
  port: <%= ENV['ENV_DB_PORT'] %>
  encoding: unicode
  pool: 50
